### ISSUE TITLE
after uploading and run on to cpanel am getting below errors 

### ISSUE THREAD

**Issue by contcat** [techwithtim/Flask-Blog-Tutorial#11]
App 2146154 output: /opt/cpanel/ea-ruby24/root/usr/share/passenger/helper-scripts/wsgi-loader.py:26: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
App 2146154 output:   import sys, os, re, imp, threading, signal, traceback, socket, select, struct, logging, errno
App 2146154 output: Traceback (most recent call last):
App 2146154 output:   File "/opt/cpanel/ea-ruby24/root/usr/share/passenger/helper-scripts/wsgi-loader.py", line 369, in <module>
App 2146154 output:     app_module = load_app()
App 2146154 output:   File "/opt/cpanel/ea-ruby24/root/usr/share/passenger/helper-scripts/wsgi-loader.py", line 76, in load_app
App 2146154 output:     return imp.load_source('passenger_wsgi', startup_file)
App 2146154 output:   File "/home/yutijjfa/virtualenv/public_html/app/webroot/pybot/3.8/lib64/python3.8/imp.py", line 171, in load_source
App 2146154 output:     module = _load(spec)
App 2146154 output:   File "<frozen importlib._bootstrap>", line 702, in _load
App 2146154 output:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
App 2146154 output:   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
App 2146154 output:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
App 2146154 output:   File "/home/yutijjfa/public_html/app/webroot/pybot/passenger_wsgi.py", line 9, in <module>
App 2146154 output:     application = wsgi.app
App 2146154 output: AttributeError: module 'wsgi' has no attribute 'app'

**Comment by shashank-pathe** [comment]
i am also getting the same , did you get solution ?

"App 324986 output: /home/user/.bashrc: line 10: alias: source: not found
App 324986 output: /home/user/.bashrc: line 10: alias: /home/t49k2ghs244c/.bashrc: not found
App 324986 output: c:26: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
App 324986 output:   import sys, os, re, imp, threading, signal, traceback, socket, select, struct, logging, errno
App 358430 output: /home/user/.bashrc: line 10: alias: source: not found"

**Comment by hrishikeshnerkar956** [comment]
Traceback (most recent call last):
  File "C:\Users\hrish\Desktop\Flask Blog Project\app.py", line 4, in <module>
t__.py", line 24, in create_app
    create_database(app)
  File "C:\Users\hrish\Desktop\Flask Blog Project\website\__init__.py", line 39, in create_database
    db.create_all(app=app)
TypeError: SQLAlchemy.create_all() got an unexpected keyword argument 'app'

i am getting this error after running.
